# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_auto_20161205_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('channel', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'logic_location',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
