# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_auto_20161206_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorKedsum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(blank=True, max_length=15, null=True)),
                ('temperature', models.CharField(blank=True, max_length=15, null=True)),
                ('humidity', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'sensor_kedsum',
            },
        ),
        migrations.CreateModel(
            name='SensorPrologue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(blank=True, max_length=15, null=True)),
                ('temperature', models.CharField(blank=True, max_length=15, null=True)),
                ('humidity', models.CharField(blank=True, max_length=15, null=True)),
                ('battery', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'sensor_prologue',
            },
        ),
        migrations.CreateModel(
            name='SensorThgr122N',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(blank=True, max_length=15, null=True)),
                ('temperature', models.CharField(blank=True, max_length=15, null=True)),
                ('humidity', models.CharField(blank=True, max_length=15, null=True)),
                ('battery', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'sensor_thgr122n',
            },
        ),
    ]
